Footer start
baza-trainee/chytozavrik-frontend pull request #18
Opened 2023-07-04 12:11 UTC by RuslanDakeshev

2023-07-11 17:22 UTC, Zaimak-Andrii requested changes

2023-07-11 17:22 UTC, Zaimak-Andrii commented on src/app/layout.tsx
> +import { Inter } from 'next/font/google';
Видалил шривт inter

2023-07-11 17:22 UTC, Zaimak-Andrii commented on src/app/layout.tsx
> +
змінити weight: ['400', '600'];

2023-07-11 17:38 UTC, Zaimak-Andrii requested changes

2023-07-11 17:38 UTC, Zaimak-Andrii commented on src/components/Footer/Footer.module.scss
> +  background: var(--ref-blue-blue-20, #455fc8);
background: getColor(blue, 40);

2023-07-11 17:38 UTC, Zaimak-Andrii commented on src/components/Footer/Footer.module.scss
> +  font-family: 'Comforta';
Передивитись шрифт

2023-07-12 13:35 UTC, olha-sydorenko commented on src/components/Footer/Footer.tsx
Ось тут 2 контейнера, 13-й і 14-й рядок, кожен з них дає падінг боковий

2023-07-12 19:28 UTC, olha-sydorenko approved these changes

2023-07-12 19:29 UTC, olha-sydorenko approved these changes

2023-07-13 12:59 UTC, Zaimak-Andrii approved these changes

2023-07-13 13:00 UTC, merged