Wigwam book list
baza-trainee/chytozavrik-frontend pull request #46
Opened 2023-07-30 18:31 UTC by yuriipanasiuk

2023-07-31 06:03 UTC, Zaimak-Andrii requested changes

2023-07-31 06:03 UTC, Zaimak-Andrii commented on src/components/common/form/Input/Input.tsx
> -    resetField: () => void;
Навіщо тут зробив параметр опційним?

2023-08-02 11:28 UTC, olha-sydorenko approved these changes

2023-08-02 11:30 UTC, olha-sydorenko approved these changes

2023-08-02 11:38 UTC, Zaimak-Andrii approved these changes

2023-08-02 11:38 UTC, merged